'use strict';

/** B-sprint v2 — 10 signals (UX-spec V2). Dry-run only. */

const REGISTRY_VERSION = '2.0.0-b-sprint';

const RULES = Object.freeze([
  {
    id: 'customer.missing_health_declaration',
    step: 3,
    what: 'Hälsodeklaration saknas',
    why: 'Krävs inför konsultation (steg 3). Pre-info och Meridiq-länk ingår i bokningsbekräftelsen (steg 2).',
    next: 'Öppna formulärstatus / patientportal',
    risk: 'blocker',
    humanApprovalRequired: true,
    suggestedRoute: null,
    confidenceDefault: 'medium',
    v1Enabled: true,
  },
  {
    id: 'customer.missing_journal',
    step: 4,
    what: 'Journal saknas',
    why: 'Konsultation (steg 4) kräver encounter och journal.',
    next: 'Öppna journal',
    risk: 'blocker',
    humanApprovalRequired: false,
    suggestedRoute: '/journal-feed-demo.html?customerId=',
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'customer.missing_treatment_plan',
    step: 5,
    what: 'Behandlingsplan/offert saknas',
    why: 'Efter konsult (steg 5) — offert = behandlingsplan.',
    next: 'Skapa/skicka behandlingsplan',
    risk: 'blocker',
    humanApprovalRequired: true,
    // Kundens portal (cco-patient-offer-portal-v3) nås via esignToken och kan
    // inte länkas statiskt. Signalen pekar därför på PERSONALENS yta — kundens
    // workspace, där offerten skapas och portaldelningen utlöses. Samma
    // mönster som övriga rutter: konsumenten hänger på patientId sist.
    suggestedRoute: '/major-arcana-preview/?view=customers&workspace=1&patientId=',
    confidenceDefault: 'low',
    v1Enabled: true,
  },
  {
    id: 'customer.cooling_off_active',
    step: 6,
    what: 'Betänketid pågår',
    why: 'Betänketid 2 dagar (steg 6). Ej bokbar för nästa steg.',
    next: 'Vänta — visa slutdatum',
    risk: 'info',
    humanApprovalRequired: false,
    suggestedRoute: null,
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'customer.cooling_off_passed',
    step: 6,
    what: 'Betänketid passerad',
    why: '2 dagar har gått — kan gå till avtal och samtycke (steg 7).',
    next: 'Fortsätt till avtal + behandlingssamtycke',
    risk: 'ready',
    humanApprovalRequired: false,
    suggestedRoute: null,
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'customer.missing_agreement_consent_bundle',
    step: 7,
    what: 'Avtal + samtycke saknas',
    why: 'Steg 7 — samma transaktion. Separata utskick är ogiltiga.',
    next: 'Legal review → bundle-signering',
    risk: 'legal_blocker',
    humanApprovalRequired: true,
    // Avtal + samtycke signeras av kunden i offertportalen via samma
    // esignToken-kedja som steg 5. Token är per kund, så signalen pekar på
    // personalens workspace där bundle-delningen utlöses.
    suggestedRoute: '/major-arcana-preview/?view=customers&workspace=1&patientId=',
    confidenceDefault: 'medium',
    v1Enabled: true,
  },
  {
    id: 'customer.missing_operation_day_insurance',
    step: 8,
    what: 'Friskförsäkran saknas',
    why: 'Operationsdagen — tablet/QR. Blockerar operationsstart.',
    next: 'Friskförsäkran på plats i kliniken',
    risk: 'blocker',
    humanApprovalRequired: false,
    suggestedRoute: null,
    confidenceDefault: 'low',
    v1Enabled: true,
  },
  {
    id: 'customer.missing_photo_consent',
    step: 9,
    what: 'Foto-samtycke saknas',
    why: 'Vid för-/efterbild — hårlinje/krona, aldrig ansikte.',
    next: 'Visa scope-prompt vid foto',
    risk: 'legal',
    humanApprovalRequired: true,
    suggestedRoute: null,
    confidenceDefault: 'low',
    v1Enabled: true,
  },
  {
    id: 'customer.has_photo_review',
    step: null,
    what: 'Bildreview väntar',
    why: 'Operatör granskar bilder — ej samma som foto-samtycke.',
    next: 'Öppna Photo Review',
    risk: 'needs_review',
    humanApprovalRequired: true,
    suggestedRoute: '/photo-review.html?focusPatientId=',
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'customer.ready_for_treatment',
    step: null,
    what: 'Redo för behandling',
    why: 'Komposit: betänketid OK + bundle + legal + ops-dag FF vid behov.',
    next: 'Öppna kalender / operationsflöde',
    risk: 'ready',
    humanApprovalRequired: false,
    suggestedRoute: '/kalender.html?patientId=',
    confidenceDefault: 'medium',
    v1Enabled: true,
  },
  {
    id: 'conversation.unanswered_inbound',
    step: null,
    what: 'Obesvarad inkommande konversation',
    why: 'Kunden har väntat på svar utan att ha fått återkoppling.',
    next: 'Öppna tråd och föreslå svar',
    risk: 'needs_review',
    humanApprovalRequired: false,
    suggestedRoute: '/cco/',
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'conversation.sla_breach',
    step: null,
    what: 'SLA-gräns passerad',
    why: 'Konversationen har överstigit klinikens svarstidsåtagande.',
    next: 'Eskalera till ansvarig och påbörja svar',
    risk: 'blocker',
    humanApprovalRequired: true,
    suggestedRoute: '/cco/',
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'conversation.frustrated_tone',
    step: null,
    what: 'Frustrerad eller missnöjd ton',
    why: 'Sentiment/signalering indikerar att kunden är missnöjd.',
    next: 'Öppna tråd och hantera med prioritering',
    risk: 'blocker',
    humanApprovalRequired: true,
    suggestedRoute: '/cco/',
    confidenceDefault: 'medium',
    v1Enabled: true,
  },
  {
    id: 'conversation.booking_request_intent',
    step: null,
    what: 'Bokningsförfrågan identifierad',
    why: 'Konversationens avsikt pekar mot att kunden vill boka tid.',
    next: 'Föreslå bokning i kalender',
    risk: 'ready',
    humanApprovalRequired: false,
    suggestedRoute: '/kalender.html?patientId=',
    confidenceDefault: 'medium',
    v1Enabled: true,
  },
  {
    id: 'conversation.follow_up_due',
    step: null,
    what: 'Uppföljning förfallen',
    why: 'En markerad uppföljning har passerat sitt förfallodatum.',
    next: 'Skapa påminnelseutkast',
    risk: 'needs_review',
    humanApprovalRequired: false,
    suggestedRoute: '/cco/',
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'customer.treatment_done_no_journal',
    step: null,
    what: 'Behandling utförd — journal saknas',
    why: 'Efter genomförd behandling måste journal föras samma dag.',
    next: 'För journal',
    risk: 'blocker',
    humanApprovalRequired: true,
    suggestedRoute: '/journal-feed-demo.html?customerId=',
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'customer.followup_due',
    step: null,
    what: 'Uppföljning förfallen',
    why: 'Schemalagd uppföljning har passerat sitt datum.',
    next: 'Boka/utför uppföljning',
    risk: 'needs_review',
    humanApprovalRequired: false,
    suggestedRoute: '/kalender.html?patientId=',
    confidenceDefault: 'high',
    v1Enabled: true,
  },
  {
    id: 'customer.followup_not_booked',
    step: null,
    what: 'Uppföljning ej bokad',
    why: 'Kunden har inte bokat sin uppföljningstid.',
    next: 'Skapa bokning',
    risk: 'needs_review',
    humanApprovalRequired: false,
    suggestedRoute: '/kalender.html?patientId=',
    confidenceDefault: 'medium',
    v1Enabled: true,
  },
  {
    id: 'customer.deposit_unpaid',
    step: null,
    what: 'Deposition obetald',
    why: '20%-depositionen från accepterad offert är inte betald.',
    next: 'Skicka betalningspåminnelse',
    risk: 'blocker',
    humanApprovalRequired: true,
    suggestedRoute: '/major-arcana-preview/?view=customers&workspace=1&patientId=',
    confidenceDefault: 'medium',
    v1Enabled: true,
  },
  {
    id: 'customer.result_ready_no_publish_consent',
    step: null,
    what: 'Resultat klart — publiceringssamtycke saknas',
    why: 'För-/efterbilder redo men kunden har inte gett publiceringssamtycke.',
    next: 'Öppna foto-samtycke',
    risk: 'legal',
    humanApprovalRequired: true,
    suggestedRoute: null,
    confidenceDefault: 'low',
    v1Enabled: true,
  },
]);

function listRules() {
  return RULES.map((rule) => ({ ...rule }));
}

function getRule(ruleId) {
  const id = String(ruleId || '').trim();
  return RULES.find((rule) => rule.id === id) || null;
}

function getCatalog() {
  return {
    version: REGISTRY_VERSION,
    dryRun: true,
    ruleCount: RULES.length,
    rules: listRules(),
    enabled: isAutomationRunnerEnabled(),
  };
}

function isAutomationRunnerEnabled() {
  return String(process.env.ENABLE_AUTOMATION_RUNNER || '').toLowerCase() === 'true';
}

module.exports = {
  REGISTRY_VERSION,
  RULES,
  listRules,
  getRule,
  getCatalog,
  isAutomationRunnerEnabled,
};
